"""empty initial migration (stamp only)

This migration is intentionally EMPTY. It only records the Alembic version state
so that subsequent autogenerated migrations are treated as incremental deltas.

Existing PostgreSQL tables (created by the legacy Django backend) MUST NOT be
recreated or dropped. Do not add create_table/drop_table/drop_column/column-type
changes here. The CI migration guard (scripts/check_migrations.py) enforces this.

Revision ID: 0001_empty
Revises:
Create Date: 2026-07-08 00:00:00.000000

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

revision: str = "0001_empty"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # 空基线：仅记录版本状态，不创建任何表（表已存在于现有 PostgreSQL）。
    pass


def downgrade() -> None:
    # 对应空基线，无操作。
    pass
